#!/bin/bash
##
##
##
##
## This edits the Mirrorlist file to only have Australian repositories
echo "Modifying the Mirrorlist file to point only to Australian Repositories !!!"
sleep 2
sed -i "s/Server/##Server/g" /etc/pacman.d/mirrorlist && sed -i '/## Austalia/{n;s/##Server/Server/}' /etc/pacman.d/mirrorlist
echo "Command executed"
##
##
echo " "
echo "Gary is the best"
echo " "
