#!/bin/bash
clear
echo "
                                 .--'   ..............             '.............'             '..............     ....''    
                              '+dmMMd  'hdmmmmmmmmmmmh             .dmmmmmmmmmmmmo             .dmmmmmmmmmmmms   :dm:.:yh    
                             +ms.hMMd  'hmmmmmmmmmmmmh             .dmmmmmmmmmmmmo             .dmdmmmmmmmmmms   :mMmhs+/    
                            hMhoomMMmo/'hmmdmmmmmmmmmy             .dmmdmmmmmmmmmo             .dmdmmmdddmmmms   o-'-/sNM:   
                            ''''/dNNm:''hmmmhyyyyyyyys.............-yyhdddmmmdmdh+.............-yhhhhhhdddmmms   syo//+h+'   
                                 ````  'hmmd+//////////////////////////hmmmmmmdd+/////////////////////odddmmms               
                                       'hmmd+//////////////////////////hddmmmmdy//////////////////////odddmmms               
                                       'hmmd+//////yhy''''.://////////odmmmmmmd+//////:........-yyyyyyhdddmmms               
                               '-/++/' 'hmmd+//////dmy  '-//////////+yddmmmmmds///////.        .dmdmmdddmmmmms               
                            '+dNd/.    'hmmd+//////dmy'.//////////::ddmmmmmmdh///////:--::::::::syhdmmmmmmmmms   .+o//+o/'   
                            hMMMoshmho''hmmdyyyyyyyddy://///////:. .dmdmmmdmdo/////////////////////+ohddmmmmms  oNN-   +MN:  
                            hMMy   NMM+'hmmdmmmmmmdh+/////////:.   .dmdmmmdmy///////::-.....-:////////+hmmmmms 'mMN    -MMs  
                            '+ydsoydy/ 'hmmmmmdmdho/////////:.     .ddddmdmmdddhh+.'          ':////////hmmmms  -hN+''.hNs'  
                                       'hmdmddmds/////////:.'  ':://+++dmdmmmmmmdo             '////////smmmms    ':+mNh.'   
                                       'hmdmdds/////////:-'    '///////dmmddhhhhh+..           .////////ydmmms       ./+/:'  
                                       'hmddy+/////////-'''''''.///////hmmdh////////-'        .:///////odmmmms               
                                       'hmdo///////////////////////////hdmmdh+////////:--..--:///////+ydmmmmms               
                             ./+ooo+-' 'hmdo///////////////////////////hddmmmdyo+//////////////////oydmmmmmmms '...'   ....' 
                            oNM+''dMMh 'hmdsooooooooo+::::::::::::::ooohmdmmmddmdo.---:::::::---yddmmdmmmmmmms ':mNNo. -yy-' 
                            '-:./hMNs. 'hmdmmmdddddddy             .dmmmmmmmmmmmmo             .dmmmmmmmmmmmms   h:oNNo.+o   
                            '/yNNy/'.:''hmmmmmmmmmmmmy             .dmmmmmmmmmmmmo             .dmmmmmmmmmmmms   h- 'oNNdo   
                            shhhyyyyhy''oyyyyyyyyyyyyo             .syyyyyyyyyyyy/             'syyyyyyyyyyyy+ .:yo-  '+h/ 
"
echo
echo
echo "                                                         VIPER MASTER BUILD SCRIPT"
echo "                                            WARNING: This will format the provided block device!"
echo
echo
echo

######################################## START OF SCRIPT ########################################

#################### Section 1.0 (Collection of data) ####################

#@read -p "Create an Arch Linux Root Password: " ROOTPASSWORD

#@read -p "Create a User?: " USERNAME

#@read -p "$USERNAME Password?: " USERPASSWORD

#@read -p "Hostname of the System?: " HOSTNAME

#@read -p "Create an Arch Linux System LUKS Passphrase: " LUKSPASSPHRASE

##read -p "WARNING: This script will wipe all data from the Harddrive /dev/sda. Are you sure you want to continue? Y or N? " InstallStart
##if      [ "${InstallStart,,}" = "yes" ] || [ "${InstallStart,,}" = "y" ]
##then    echo "Installing Arch Linux !!!" && sleep 2s
##else    exit && echo "Installation Aborted !!!"
##fi

#################### Section 2.0 (Delete Hard Drive Partitions) ####################

#@dd if=/dev/zero of=/dev/sda bs=512 count=1 conv=notrunc
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 3.0 (Configure Repository Locations - HTTPS priority) ####################

#@sed -i "s/#Color/Color/" /etc/pacman.conf && sed -i '/^#VerbosePkgLists/a ILoveCandy' /etc/pacman.conf
#@sed -i "s/Server/##Server/g" /etc/pacman.d/mirrorlist && sed -i '/## Australia/{n;s/##Server/Server/}' /etc/pacman.d/mirrorlist
#@sed -i '/## Generated on/a Server = https://mirror.aarnet.edu.au/pub/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist
#@sed -i '/## Generated on/a Server = https://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch' /etc/pacman.d/mirrorlist
#@sed -i '/## Generated on/a Server = https://syd.mirror.rackspace.com/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist

#################### Section 4.0 (Download Latest Arch Linux Packages) ####################

#@pacman -Syyy
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s


#################### Section 5.0 (Install Expect Shell) ####################

#@printf '\n\n\n' | pacman -Syy expect
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 6.0 (Setup HDD Partitions for Installation) ####################

#@echo "label: gpt" > partition-table
#@echo "device: /dev/sda" >> partition-table
#@echo "unit: sectors" >> partition-table
#@echo "first-lba: 2048" >> partition-table
#@echo "last-lba: 1000215182" >> partition-table
#@echo " " >> partition-table
#@echo "/dev/sda1 : start=           2048, size=   2097152, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B"   >> partition-table
#@echo "/dev/sda2 : start=        2099200, size=   8388608, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4"   >> partition-table
#@echo "/dev/sda3 : start=       10487808, size=   989727375, type=E6D6D379-F507-44C2-A23C-238F2A3DF928" >> partition-table
#@sleep 2s
#@sfdisk /dev/sda < partition-table
#@rm partition-table
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 7.0 (Format SDA1 Boot Partition) ####################

#@mkfs.fat -F32 /dev/sda1
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 8.0 (Format SDA2 Swap Partition) ####################

#@printf 'y\n' | mkfs.ext4 /dev/sda2
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 9.0 (Setup of SDA 3 LUKS Partition Encrypted Container) ####################

#@echo "#!/usr/bin/expect -f" > expectfile
#@echo "set send_slow {2 0.5}" >> expectfile
#@echo "spawn cryptsetup luksFormat /dev/sda3" >> expectfile
#@echo "expect \"Are you sure? (Type 'yes' in capital letters):\\r\"" >> expectfile
#@echo "send -s \"YES\\r\"" >> expectfile
#@echo "expect \"Enter passphrase for /dev/sda3:\\r\"" >> expectfile
#@echo "send -s \"$LUKSPASSPHRASE\\r\"" >> expectfile
#@echo "expect \"Verify passphrase:\\r\"" >> expectfile
#@echo "send -s \"$LUKSPASSPHRASE\\r\"" >> expectfile
#@echo "interact" >> expectfile
#@chmod 777 expectfile
#@expect expectfile
#@sleep 5s
#@rm expectfile
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 10.0 (Open LUKS Container) ####################

#@printf '%s\n' "$LUKSPASSPHRASE" | cryptsetup open --type luks /dev/sda3 lvm
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 11.0 (Setup Physical Volume) ####################

#@pvcreate --dataalignment 1m /dev/mapper/lvm
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 12.0 (Setup Virtual Volume Group) ####################

#@vgcreate volgroup0 /dev/mapper/lvm
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 13.0 (Setup Live Volumes for LUKS Encrypted Drive) ####################

#@lvcreate -L 50GB volgroup0 -n lv_root
#@sleep 2s
#@## lvcreate -L 350GB volgroup0 -n lv_home
#@lvcreate -l 100%FREE volgroup0 -n lv_home
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 14.0 (Create Root Filesystem for LUKS encrypted drive) ####################

#@mkfs.ext4 /dev/volgroup0/lv_root
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 15.0 (Create Home Filesystem for LUKS encrypted drive) ####################

#@mkfs.ext4 /dev/volgroup0/lv_home
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 16.0 (Mount Home and Boot Volumes) ####################

#@mount /dev/volgroup0/lv_root /mnt
#@sleep 2s
#@mkdir /mnt/home
#@mount /dev/volgroup0/lv_home /mnt/home
#@sleep 2s
#@mkdir /mnt/boot
#@mount /dev/sda2 /mnt/boot
#@sleep 2s
#@mkdir /mnt/etc
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 17.0 (Configures Filesystem Table for Boot) ####################

#@genfstab -U -p /mnt >> /mnt/etc/fstab
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 18.0 (Download Base Arch Linux into Mount location) ####################

#@printf '\n\n\n' | pacstrap -i /mnt base
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 19.0 (Install Linux LTS Version to CHROOT) ####################

###note need to install firmware (aic94xx;wd719x)

#@printf '\n\n\n' | arch-chroot /mnt pacman -S linux-lts linux-lts-headers
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 20.0 (Install Linux Firmware to CHROOT) ####################

#@printf '\n\n\n' | arch-chroot /mnt pacman -S linux-firmware
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 21.0 (Install Text Editor Packages to CHROOT) ####################

#@printf '\n\n\n' | arch-chroot /mnt pacman -S nano vim
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 22.0 (Install Base Developer Packages and SSH to CHROOT) ####################

#@printf '\n\n\n' | arch-chroot /mnt pacman -S base-devel openssh
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt systemctl enable sshd
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 23.0 (Install Networking Utility Packages to CHROOT) ####################

#@printf '\n\n\n' | arch-chroot /mnt pacman -S networkmanager wpa_supplicant wireless_tools netctl
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt systemctl enable NetworkManager
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt systemctl enable dhcpcd
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 24.0 (Install Dialog to CHROOT) ####################

#@printf '\n\n\n' | arch-chroot /mnt pacman -S dialog
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 25.0 (Install LVM2 Packages to CHROOT) ####################

#@printf '\n\n\n' | arch-chroot /mnt pacman -S lvm2
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 26.0 (Enable Encryption and LVM2 functionality to CHROOT) ####################

#@arch-chroot /mnt sed -i "s/block/block encrypt lvm2/" /etc/mkinitcpio.conf
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt mkinitcpio -p linux-lts
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 27.0 (Configure Language and Locale Settings) ####################

#@arch-chroot /mnt sed -i "s/#en_AU.UTF-8/en_AU.UTF-8/" /etc/locale.gen
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt locale-gen
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@echo "LANG=en_AU.UTF-8" > /mnt/etc/locale.conf
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@cp /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 28.0 (Configure Hostname) ####################

#@echo "$HOSTNAME" > /mnt/etc/hostname
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 29.0 (Configure Hosts File) ####################

#@echo "127.0.0.1  localhost" >> /mnt/etc/hosts
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@echo "::1  localhost" >> /mnt/etc/hosts
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@echo "127.0.1.1  $HOSTNAME.localdomain $HOSTNAME" >> /mnt/etc/hosts
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 30.0 (Install Sudo and Setup Root Level Password) ####################

#@printf '\n\n\n' | arch-chroot /mnt pacman -S sudo
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@printf "$ROOTPASSWORD\n$ROOTPASSWORD" | arch-chroot /mnt passwd
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 31.0 (Setup Users and Groups) ####################

#@arch-chroot /mnt useradd -m -g users -G wheel $USERNAME
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@printf "$USERPASSWORD\n$USERPASSWORD" | arch-chroot /mnt passwd $USERNAME
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 31.0 (Enable Wheel Group) ####################

#@sudo sed -i 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+ALL\)/\1/' /etc/sudoers
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 32.0 (Download GRUB Bootloader Software Packages) ####################

#@printf '\n\n\n' | arch-chroot /mnt pacman -S grub efibootmgr dosfstools os-prober mtools
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 33.0 (Configure Encryption GRUB Boot) ####################

#@arch-chroot /mnt sed -i "s/#GRUB_ENABLE_CRYPTODISK=y/GRUB_ENABLE_CRYPTODISK=y/" /etc/default/grub
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt sed -i "s/GRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=3 quiet\"/GRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=3 cryptdevice=\/dev\/sda3:volgroup0:allow-discards quiet\"/" /etc/default/grub
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 34.0 (Setup and Enable EFI Booting) ####################

#@arch-chroot /mnt mkdir /boot/EFI
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt mount /dev/sda1 /boot/EFI
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 35.0 (Install GRUB Bootloader) ####################

#@arch-chroot /mnt grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 36.0 (Setup and Enable Location Settings for Boot) ####################

#@arch-chroot /mnt mkdir /boot/grub/locale
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 37.0 (Create and Setup Swapfile) ####################

#@arch-chroot /mnt fallocate -l 4G /swapfile
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt chmod 600 /swapfile
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt mkswap /swapfile
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 38.0 (Backup FSTAB file) ####################

#@arch-chroot /mnt cp /etc/fstab /etc/fstab.bak
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 39.0 (Setup Swapfile Boot Configuration) ####################

#@echo '/swapfile none swap sw 0 0' >> /mnt/etc/fstab
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 40.0 (Install Intel Software Packages) ####################

#@printf '\n\n\n' | arch-chroot /mnt pacman -S intel-ucode
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 41.0 (Install GUI Base Software) ####################

#@printf '\n\n\n' |  arch-chroot /mnt pacman -S xorg xorg-server
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 42.0 (Install MESA Package) ####################

#@printf '\n\n\n' |  arch-chroot /mnt pacman -S mesa
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 43.0 (Install GNOME Desktop and Configuration for Boot) ####################

#@printf '\n\n\n\n\n\n\n\n' | arch-chroot /mnt pacman -S gnome gnome-extra
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt systemctl start gdm.service
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#@arch-chroot /mnt systemctl enable gdm.service
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 44.0 (Unmount All prior to reboot) ####################

#@umount -a
#@echo " "
#@echo " "
#@echo " "
#@sleep 2s

#################### Section 44.0 (Power Off and Remove USB) ####################

#@ #echo "Shutting System Down. Once System has Powered off, remove USB thumbdrive and then Power ON !!!"
#@ # press any key to continue funtion

######################################## END OF SCRIPT ########################################
