#!/bin/bash
##
##
##
##
## This edits the Mirrorlist file to only have Australian repositories
echo "Modifying the Mirrorlist file to point only to Australian Repositories !!!"
sleep 2
sudo sed -i "s/Server/##Server/g" /etc/pacman.d/mirrorlist && sudo sed -i '/## Australia/{n;s/##Server/Server/}' /etc/pacman.d/mirrorlist
echo "Command executed"
##
##
echo " "
echo "Gary is the best"
echo " "
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk ${TGTDEV}
o # clear the in memory partition table
n # new partition
p # primary partition
1 # partition number 1
 # default - start at beginning of disk 
+100M # 100 MB boot parttion
n # new partition
p # primary partition
2 # partion number 2
  # default, start immediately after preceding partition
  # default, extend partition to end of disk
a # make a partition bootable
1 # bootable partition is partition 1 -- /dev/sda1
p # print the in-memory partition table
w # write the partition table
q # and we're done
EOF
