#!/bin/bash
clear
echo "
                       .--'   ..............             '.............'             '..............     ....''    
                    '+dmMMd  'hdmmmmmmmmmmmh             .dmmmmmmmmmmmmo             .dmmmmmmmmmmmms   :dm:.:yh    
                   +ms.hMMd  'hmmmmmmmmmmmmh             .dmmmmmmmmmmmmo             .dmdmmmmmmmmmms   :mMmhs+/    
                  hMhoomMMmo/'hmmdmmmmmmmmmy             .dmmdmmmmmmmmmo             .dmdmmmdddmmmms   o-'-/sNM:   
                  ''''/dNNm:''hmmmhyyyyyyyys.............-yyhdddmmmdmdh+.............-yhhhhhhdddmmms   syo//+h+'   
                       ````  'hmmd+//////////////////////////hmmmmmmdd+/////////////////////odddmmms               
                             'hmmd+//////////////////////////hddmmmmdy//////////////////////odddmmms               
                             'hmmd+//////yhy''''.://////////odmmmmmmd+//////:........-yyyyyyhdddmmms               
                     '-/++/' 'hmmd+//////dmy  '-//////////+yddmmmmmds///////.        .dmdmmdddmmmmms               
                  '+dNd/.    'hmmd+//////dmy'.//////////::ddmmmmmmdh///////:--::::::::syhdmmmmmmmmms   .+o//+o/'   
                  hMMMoshmho''hmmdyyyyyyyddy://///////:. .dmdmmmdmdo/////////////////////+ohddmmmmms  oNN-   +MN:  
                  hMMy   NMM+'hmmdmmmmmmdh+/////////:.   .dmdmmmdmy///////::-.....-:////////+hmmmmms 'mMN    -MMs  
                  '+ydsoydy/ 'hmmmmmdmdho/////////:.     .ddddmdmmdddhh+.'          ':////////hmmmms  -hN+''.hNs'  
                             'hmdmddmds/////////:.'  ':://+++dmdmmmmmmdo             '////////smmmms    ':+mNh.'   
                             'hmdmdds/////////:-'    '///////dmmddhhhhh+..           .////////ydmmms       ./+/:'  
                             'hmddy+/////////-'''''''.///////hmmdh////////-'        .:///////odmmmms               
                             'hmdo///////////////////////////hdmmdh+////////:--..--:///////+ydmmmmms               
                   ./+ooo+-' 'hmdo///////////////////////////hddmmmdyo+//////////////////oydmmmmmmms '...'   ....' 
                  oNM+''dMMh 'hmdsooooooooo+::::::::::::::ooohmdmmmddmdo.---:::::::---yddmmdmmmmmmms ':mNNo. -yy-' 
                  '-:./hMNs. 'hmdmmmdddddddy             .dmmmmmmmmmmmmo             .dmmmmmmmmmmmms   h:oNNo.+o   
                  '/yNNy/'.:''hmmmmmmmmmmmmy             .dmmmmmmmmmmmmo             .dmmmmmmmmmmmms   h- 'oNNdo   
                  shhhyyyyhy''oyyyyyyyyyyyyo             .syyyyyyyyyyyy/             'syyyyyyyyyyyy+ .:yo-  '+h/ 
"
echo
echo
echo "                                               VIPER MASTER BUILD SCRIPT"
echo "                                   WARNING: This will format the provided block device!"
echo
echo
echo

######################################## START OF SCRIPT ########################################

#################### Section 1.0 (Collection of data) ####################

#@read -p "Create an Arch Linux Root Password: " ROOTPASSWORD
#@
#@
#@
read -p "Hostname of the System?: " HOSTNAME
read -p "Create an Arch Linux System LUKS Passphrase: " LUKSPASSPHRASE

##read -p "WARNING: This script will wipe all data from the Harddrive /dev/sda. Are you sure you want to continue? Y or N? " InstallStart
##if      [ "${InstallStart,,}" = "yes" ] || [ "${InstallStart,,}" = "y" ]
##then    echo "Installing Arch Linux !!!" && sleep 2s
##else    exit && echo "Installation Aborted !!!"
##fi

#################### Section 2.0 (Delete Hard Drive Partitions) ####################

#@dd if=/dev/zero of=/dev/sda bs=512 count=1 conv=notrunc
#@sleep 2s

#################### Section 3.0 (Configure Repository Locations - HTTPS priority) ####################

#@sed -i "s/#Color/Color/" /etc/pacman.conf && sed -i '/^#VerbosePkgLists/a ILoveCandy' /etc/pacman.conf
#@sed -i "s/Server/##Server/g" /etc/pacman.d/mirrorlist && sed -i '/## Australia/{n;s/##Server/Server/}' /etc/pacman.d/mirrorlist
#@sed -i '/## Generated on/a Server = https://mirror.aarnet.edu.au/pub/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist
#@sed -i '/## Generated on/a Server = https://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch' /etc/pacman.d/mirrorlist
#@sed -i '/## Generated on/a Server = https://syd.mirror.rackspace.com/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist

#################### Section 4.0 (Install Expect Shell) ####################

#@printf '\n' | pacman -Syy expect
#@sleep 2s

#################### Section 5.0 (Download Latest Arch Linux Packages) ####################

#@pacman -Syyy
#@sleep 2s

#################### Section 6.0 (Setup HDD Partitions for Installation) ####################

#@echo "label: gpt" > partition-table
#@echo "device: /dev/sda" >> partition-table
#@echo "unit: sectors" >> partition-table
#@echo "first-lba: 2048" >> partition-table
#@echo "last-lba: 1000215182" >> partition-table
#@echo " " >> partition-table
#@echo "/dev/sda1 : start=           2048, size=   2097152, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B"   >> partition-table
#@echo "/dev/sda2 : start=        2099200, size=   8388608, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4"   >> partition-table
#@echo "/dev/sda3 : start=       10487808, size=   989727375, type=E6D6D379-F507-44C2-A23C-238F2A3DF928" >> partition-table
#@sleep 2s
#@sfdisk /dev/sda < partition-table
#@rm partition-table
#@sleep 5s

#################### Section 7.0 (Format SDA1 Boot Partition) ####################

#@mkfs.fat -F32 /dev/sda1
#@sleep 5s

#################### Section 8.0 (Format SDA2 Swap Partition) ####################

#@printf 'y\n' | mkfs.ext4 /dev/sda2
#@sleep 5s

#################### Section 9.0 (Setup of SDA 3 LUKS Partition Encrypted Container) ####################

#@echo "#!/usr/bin/expect -f" > expectfile
#@echo "set send_slow {2 0.5}" >> expectfile
#@echo "spawn cryptsetup luksFormat /dev/sda3" >> expectfile
#@echo "expect \"Are you sure? (Type 'yes' in capital letters):\\r\"" >> expectfile
#@echo "send -s \"YES\\r\"" >> expectfile
#@echo "expect \"Enter passphrase for /dev/sda3:\\r\"" >> expectfile
#@echo "send -s \"$LUKSPASSPHRASE\\r\"" >> expectfile
#@echo "expect \"Verify passphrase:\\r\"" >> expectfile
#@echo "send -s \"$LUKSPASSPHRASE\\r\"" >> expectfile
#@echo "interact" >> expectfile
#@chmod 777 expectfile
#@expect expectfile
#@sleep 5s
#@rm expectfile
#@sleep 5s

#################### Section 10.0 (Open LUKS Container) ####################

#@printf '%s\n' "$LUKSPASSPHRASE" | cryptsetup open --type luks /dev/sda3 LVM
#@sleep 5s

#################### Section 11.0 (Setup Physical Volume) ####################

#@pvcreate --dataalignment 1m /dev/mapper/LVM
#@sleep 2s

#################### Section 12.0 (Setup Virtual Volume Group) ####################

#@vgcreate volgroup0 /dev/mapper/LVM
#@sleep 2s

#################### Section 13.0 (Setup Live Volumes for LUKS Encrypted Drive) ####################

#@lvcreate -L 50GB volgroup0 -n LVM_root
#@sleep 2s
#@## lvcreate -L 350GB volgroup0 -n LVM_home
#@lvcreate -l 100%FREE volgroup0 -n LVM_home
#@sleep 2s
#@sleep 5s

#################### Section 14.0 (Create Root Filesystem for LUKS encrypted drive) ####################

#@mkfs.ext4 /dev/volgroup0/LVM_root
#@sleep 2s

#################### Section 15.0 (Create Home Filesystem for LUKS encrypted drive) ####################

#@mkfs.ext4 /dev/volgroup0/LVM_home
#@sleep 2s

#################### Section 16.0 (Mount Home and Boot Volumes) ####################

#@mount /dev/volgroup0/LVM_root /mnt
#@sleep 2s
#@mkdir /mnt/home
#@mount /dev/volgroup0/LVM_home /mnt/home
#@sleep 2s
#@mkdir /mnt/boot
#@mount /dev/sda2 /mnt/boot
#@sleep 2s
#@mkdir /mnt/etc
#@sleep 2s

#################### Section 17.0 (Download Base Arch Linux into Mount location) ####################

#@printf '\n' | pacstrap -i /mnt base
#@sleep 5s

#################### Section 18.0 (Configures Filesystem Table for Boot) ####################

#@genfstab -U -p /mnt >> /mnt/etc/fstab
#@sleep 2s

#################### Section 19.0 (Configure Language and Locale Settings) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@ln -s /usr/share/zoneinfo/Australia/Adelaide /etc/localtime
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@hwclock --systohc --utc
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@locale-gen
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@echo "LANG=en_AU.UTF-8" > /etc/locale.conf
#@EOF
#@cp /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist

#################### Section 20.0 (Configure Hostname) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@echo "$HOSTNAME" > /etc/hostname
#@EOF

#################### Section 21.0 (Configure Hosts File) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@echo "127.0.0.1  localhost" > /etc/hosts
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@echo "::1  localhost" >> /etc/hosts
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@echo "127.0.1.1  $HOSTNAME.localdomain $HOSTNAME" >> /etc/hosts
#@EOF

#################### Section 22.0 (Install Base Linux Packages and Firmware to CHROOT) ####################

###note need to install firmware (aic94xx;wd719x)

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' | pacman -S
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' | pacman -S linux linux-headers linux-firmware
#@EOF

#################### Section 23.0 (Install Text Editor Packages to CHROOT) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' | pacman -S nano vim
#@EOF

#################### Section 24.0 (Install Base Developer Packages and SSH to CHROOT) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' | pacman -S base-devel openssh
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@systemctl enable sshd
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@systemctl enable dhcpcd
#@EOF

#################### Section 25.0 (Install Networking Utility Packages to CHROOT) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' | pacman -S networkmanager wpa_supplicant wireless_tools netctl
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@systemctl enable NetworkManager
#@EOF

#################### Section 26.0 (Install LVM2 Packages to CHROOT) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' | pacman -S lvm2
#@EOF

#################### Section 27.0 (Enable Encryption and LVM2 functionality to CHROOT) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@sed -i '/HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)/{s/block/block encrypt lvm2}' /etc/mkinitcpio.conf
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@mkinitcpio -p linux
#@EOF


#################### Section 28.0 (Install Sudo and Setup Root Level Password) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' |pacman -S sudo
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@ #printf '%s\n%s\n' "$ROOTPASSWORD" "$ROOTPASSWORD" | sudo passwd
#@EOF

#################### Section 29.0 (Setup Users and Groups) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@useradd -m -g admins <USERNAME> passwd PASSWORD
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@useradd -m -g users <USERNAME> passwd PASSWORD
#@EOF

#################### Section 30.0 (Download GRUB Bootloader Software Packages) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' |pacman -S grub efibootmgr dosfstools os-prober mtools
#@EOF

#################### Section 31.0 (Configure Encryption GRUB Boot) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@sed -i "s/#GRUB_ENABLE_CRYPTODISK=y/GRUB_ENABLE_CRYPTODISK=y/" /etc/default/grub
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@sed -i "s/GRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=3 quiet\"/GRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=3 cryptdevice=\/dev\/sda3:volgroup0:allow-discards quiet\"/" /etc/default/grub
#@EOF

#################### Section 32.0 (Setup and Enable EFI Booting) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@mkdir /boot/EFI
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@mount /dev/sda1 /boot/EFI
#@EOF

#################### Section 33.0 (Install GRUB Bootloader) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
#@EOF

#################### Section 34.0 (Setup and Enable Location Settings for Boot) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@mkdir /boot/grub/locale
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@cp /usr/share/locale/en@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@grub-mkconfig -o /boot/grub/grub.cfg
#@EOF

#################### Section 35.0 (Create and Setup Swapfile) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@fallocate -l 2G /swapfile
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@chmod 600 /swapfile
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@mkswap /swapfile
#@EOF

#################### Section 36.0 (Backup FSTAB file) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@cp /etc/fstab /etc/fstab.bak
#@EOF

#################### Section 37.0 (Setup Swapfile Boot Configuration) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab
#@EOF

#################### Section 38.0 (Install Intel Software Packages) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' | pacman -S intel-ucode
#@EOF

#################### Section 39.0 (Install GUI Base Software) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' |  pacman -S xorg xorg-server
#@EOF

#################### Section 40.0 (Install MESA Package) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' |  pacman -S mesa
#@EOF

#################### Section 41.0 (Install GNOME Desktop and Configuration for Boot) ####################

#@arch-chroot /mnt /bin/sh << EOF
#@printf '\n\n\n' |  pacman -S gnome gnome-extra
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@systemctl start gdm.service
#@EOF
#@arch-chroot /mnt /bin/sh << EOF
#@systemctl enable gdm.service
#@EOF

#################### Section 42.0 (Power Off and Remove USB) ####################

#@ #echo "Shutting System Down. Once System has Powered off, remove USB thumbdrive and then Power ON !!!"
#@ # press any key to continue funtion

######################################## END OF SCRIPT ########################################
