#!/bin/bash

## This Script will setup the Raspberry Pi to use an SSD for very fast speeds
## Firstly flash an old Micro SD Card and the SSD with the exact same System Image so that it is like a clone.
## Include the file called SSH on both the Micro SD and SSD.

## Create a backup of the CMDLINE file. Just in case.
sudo cp /boot/cmdline.txt /boot/cmdline.txt.bak

## Setup the Partition with the PartUUID of 0xd34db33f using fdisk. Note to Self -  make a partition file and use sfdisk to use it.
sudo echo "label: dos" > partition-table
sudo echo "label-id: 0xd34db33f" > partition-table
sudo echo "device: /dev/sda" >> partition-table
sudo echo "unit: sectors" >> partition-table
sudo echo " " >> partition-table
sudo echo "/dev/sda1 : start=           8192, size=   524288,   type=c"    >>  partition-table
sudo echo "/dev/sda2 : start=         532480, size=   13770752, type=83"   >>  partition-table
sleep 2s
sudo sfdisk /dev/sda < partition-table
sleep 5s

## Use sed to change PartUUID inside the cmdline file. Find root=PARTUUID=????????-02 and change it to root=PARTUUID=d34db33f-02
sudo sed -i "s/root=PARTUUID=[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-02/root=PARTUUID=d34db33f-02/" /boot/cmdline.txt

## Try to skip over this part to make just the one script.
#@sudo reboot

## Use sed to change PartUUID in the /etc/fstab from PARTUUID=????????-02 to PARTUUID=d34db33f-02
sudo sed -i "s/PARTUUID=[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-02/PARTUUID=d34db33f-02/" /etc/fstab

## Reboot again
sudo reboot

## Delete 2nd partition /dev/sda2 using fdisk and recreate it to use the rest of the space on the disk

#@sudo resize2fs /dev/sda2

## Check the partition worked out fine.
#@df -h

## Once completed update the system.
#@sudo apt-get update && sudo apt-get upgrade -y

## Run Benchmark test to find out if the script works or not.
#@sudo curl https://raw.githubusercontent.com/TheRemote/PiBenchmarks/master/Storage.sh | sudo bash
