#!/bin/bash

# This Script will setup the Raspberry Pi to use an SSD for very fast speeds
# Firstly flash an old Micro SD Card and the SSD with the exact same System Image so that it is like a clone.
# Include the file called SSH on both the Micro SD and SSD.

# Setup the Partition with the PartUUID of 0xd34db33f using fdisk. Note to Self -  make a partition file and use sfdisk to use it.

# Create a backup of the CMDLINE file. Just in case.
sudo cp /boot/cmdline.txt /boot/cmdline.txt.bak

# Use sed to change PartUUID inside the cmdline file. Find root=PARTUUID=????????-02 and change it to root=PARTUUID=d34db33f-02
#sed -i "s/root=PARTUUID=[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-02/root=PARTUUID=d34db33f-02/" /boot/cmdline.txt

# Try to skip over this part to make just the one script.
#sudo reboot

# Use sed to change PartUUID in the /etc/fstab from PARTUUID=????????-02 to PARTUUID=d34db33f-02
#sed -i "s/PARTUUID=[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-02/PARTUUID=d34db33f-02/" /etc/fstab

# Reboot again
#sudo reboot

# Delete 2nd partition /dev/sda2 using fdisk and recreate it to use the rest of the space on the disk

#sudo resize2fs /dev/sda2

# Check the partition worked out fine.
#df -h

# Once completed update the system.
#sudo apt-get update && sudo apt-get upgrade -y
